export const metadata = {
  title: "Admin Portal | manage your content",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div>
     {children}
    </div>
  );
}
